name: Run Tests

on:
  push:
    branches:
      - main
  release:
    types:
      - created

env:
  EMAILKEY: ${{secrets.EMAILKEY}}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: access to secrets
        run: |
          echo "MAP_API_KEY=$MAP_API_KEY" >> .env
        env:
          MAP_API_KEY: ${{secrets.MAP_API_KEY}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


          
